[workspace]
members = ["bsan-rt", "bsan-script", "cargo-bsan"]
default-members = ["bsan-script", "cargo-bsan"]
exclude = ["fiona-rs", "tests/test-cargo-bsan"]
resolver = "3"

[package]
name = "bsan"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
colored = "3"
ui_test = "0.30.7"
rustc_version = "0.4"
regex = "1.12.4"
tempfile = "3"
libc = "0.2.186"

[[test]]
name = "ui"
harness = false
