artifact_url = "https://github.com/BorrowSanitizer/rust/releases/download/"
tag = "rolling-1.93.0-dev-f8fc425"
sha = "f8fc425f41f10c0e1e06bb9e9553e27a16f1b53f"
version = "1.93.0-dev"
dependencies = ["cmake", "ninja", "curl", "clang", "clang-tidy", "clang-format", "python3"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
