artifact_url = "https://github.com/BorrowSanitizer/rust/releases/download/"
tag = "rolling-1.95.0-dev-ba37935"
sha = "ba3793526ace9cabdf3e8502ad993aafd65f32c8"
version = "1.95.0-dev"
dependencies = ["cmake", "ninja", "curl", "clang", "clang-tidy", "python3"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
llvm_branch = "rustc/21.1-2025-08-01"
llvm_url = "https://github.com/rust-lang/llvm-project.git"
