[package]
name = "bsan_rt"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { version = "0.2.178", default-features = false }
hashbrown = { version = "0.16", default-features = false, features = ["default-hasher", "nightly", "inline-more"] }
rustc-hash = { version = "2.1.1", default-features = false }
libc-print = { version = "0.1.23" }
spin = "0.10.0"
bytemuck = { version = "1.21", default-features = false }
smallvec = "1.15.1"
bitflags = "2.11.1"

[lib]
name = "bsan_rt_core"
crate-type = ["staticlib"]

[features]
default = ["pic"]
pic = []
debug = []
expensive-consistency-checks = []