on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, edited, synchronize]


env:
  BENCHER_PROJECT: '244e3ab7-f904-4240-a4f1-53695a02b061'

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Continous benchmarking with bencher
        run: |
            ./bencher.sh ${{ BENCHER_PROJECT }} ${{ secrets.BENCHER_API_TOKENS }}
          
