name: Bench
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
env:
  CARGO_TERM_COLOR: always
  BENCHER_PROJECT: '244e3ab7-f904-4240-a4f1-53695a02b061'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: '${{ matrix.config.os }}'
    container:
      image: ghcr.io/borrowsanitizer/bsan:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    name: '${{ matrix.config.target }}'
    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      run: |
        ln -s /root/.rustup/ $HOME/.rustup
        sudo apt-get update && sudo apt-get install -y hyperfine jq
    - uses: bencherdev/bencher@main
    - name: Bencher
      run: |
          ./bencher.sh $BENCHER_PROJECT '${{ secrets.BENCHER_API_TOKENS }}' /github/home/.cargo/bin/bencher --testbed 'Github-CI_${{ matrix.config.os }}'


       
        

