name: CI
on:
  push:
    branches: [ "main", "obraunsdorf/bencherdev" ]  # TODO: remove obraunsdorf/bencherdev after merging the bencher.dev integration
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
env:
  CARGO_TERM_COLOR: always
  BENCHER_PROJECT: '244e3ab7-f904-4240-a4f1-53695a02b061'


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: '${{ matrix.config.os }}'
    container:
      image: ghcr.io/borrowsanitizer/bsan:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    name: '${{ matrix.config.target }}'
    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      run: |
        ln -s /root/.rustup/ $HOME/.rustup
    - name: CI
      run: ./xb ci
    - name: Install Bencher.dev CLI
      run: | # FIXME: installing like this is only necessary because the github "action bencherdev/bencher@main is not allowed in BorrowSanitizer/bsan". Otherwise we could just do "uses: bencherdev/bencher@main" and skip the installation step
          curl --proto '=https' --tlsv1.2 -sSfL https://bencher.dev/download/install-cli.sh | sh
          source $HOME/.cargo/env
          bencher --version
    - name: Continuous benchmarking with bencher.dev
      run: |
          ./bencher.sh $BENCHER_PROJECT '${{ secrets.BENCHER_API_TOKENS }}' /github/home/.cargo/bin/bencher


       
        

