name: CI (base)
on:
  workflow_call:
    inputs:
      cache_container:
        type: boolean
        description: Require rebuilding the dev container.
        required: true

      push_container:
        type: boolean
        description: Push the dev container.
        required: true
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: '${{ matrix.config.os }}'
    name: '${{ matrix.config.target }}'

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      if: ${{ inputs.push_container }}
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: CI (rebuild dev container)
      if: ${{ ! inputs.cache_container }}
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/BorrowSanitizer/dev-${{ matrix.config.os }}
        runCmd: xb ci

    - name: CI (cached container)
      if: ${{ inputs.cache_container }}
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/BorrowSanitizer/dev-${{ matrix.config.os }}
        cacheFrom: ghcr.io/BorrowSanitizer/dev-${{ matrix.config.os }}
        runCmd: xb ci