name: image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: "image"
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/borrowsanitizer/bsan
  COMPRESSION: .tar.xz
  
jobs:
    cleanup:
      runs-on: ubuntu-latest
      steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3.0.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Fetch multi-platform package version SHAs
          id: multi-arch-digests
          run: |
            package=$(docker manifest inspect ghcr.io/borrowsanitizer/bsan | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
            echo "multi-arch-digests=$package" >> $GITHUB_OUTPUT
        - uses: snok/container-retention-policy@v3.0.1
          with:
            account: borrowsanitizer
            token: ${{ secrets.GITHUB_TOKEN }}
            image-names: bsan
            cut-off: 3mo
            skip-shas: ${{ steps.multi-arch-digests.outputs.multi-arch-digests }}
            tag-selection: both